#Q:1
Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is of type list while the variable array_list is of type numpy.ndarray.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of variable list_:", type(list_))
print("Data type of variable array_list:", type(array_list))


Data type of variable list_: <class 'list'>
Data type of variable array_list: <class 'numpy.ndarray'>


In [2]:
#Q:2
list_ = ['1', '2', '3', '4', '5']
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [3]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [4]:
#Q:3
import numpy as np

# original list
list_ = ['1', '2', '3', '4', '5']

# creating numpy array from list
array_list = np.array(object=list_)

# printing data type of each element in list_
for element in list_:
    print(type(element))

# printing data type of each element in array_list
for element in array_list:
    print(type(element))

# changing dtype of array_list
array_list = np.array(object=list_, dtype=int)

# printing data type of each element in list_
for element in list_:
    print(type(element))

# printing data type of each element in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [5]:
#Q:4
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# shape of num_array
print("Shape of num_array:", num_array.shape)

# size of num_array
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [6]:
#Q:5
import numpy as np

# creating numpy array of zeros with shape (3,3)
zeros_array = np.zeros(shape=(3, 3))

print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Q:6
import numpy as np

# creating identity matrix of shape (5,5)
identity_matrix = np.eye(N=5)

print(identity_matrix)
