TensorFlow provides several data structures to represent and manipulate data efficiently. Here are some of the commonly used data structures in TensorFlow:

1. Tensors: Tensors are the primary data structure in TensorFlow and represent multi-dimensional arrays. They can have a dynamic shape and store numerical data. Tensors are used to represent inputs, outputs, and intermediate values in computations. TensorFlow tensors are similar to numpy arrays.

2. Constants: Constants are tensors whose values cannot be changed once defined. They are typically used to store fixed values, such as hyperparameters or model parameters that do not require updates during training.

3. Variables: Variables are tensors that can hold mutable state. They are used to store and update trainable parameters during training, such as weights and biases of a neural network. Variables are initialized with an initial value and can be modified using assign operations.

4. Placeholders: Placeholders are tensors used to represent inputs to a computational graph. They allow data to be fed into the graph during the execution phase. Placeholders are commonly used in TensorFlow versions prior to 2.0. In TensorFlow 2.0 and later, the recommended approach is to use `tf.data` API for input pipeline management.

Now, let's discuss the difference between TensorFlow constants and variables with an example:

TensorFlow Constants:
```python
import tensorflow as tf

# Define a constant tensor
constant_tensor = tf.constant([1, 2, 3])

# Print the constant tensor
print(constant_tensor)
```
Output:
```
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
```
In this example, `tf.constant` creates a constant tensor with values [1, 2, 3]. The constant tensor cannot be modified after its creation. It is useful for storing fixed values like hyperparameters.

TensorFlow Variables:
```python
import tensorflow as tf

# Define a variable tensor
variable_tensor = tf.Variable([1, 2, 3])

# Print the variable tensor
print(variable_tensor)
```
Output:
```
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
```
In this example, `tf.Variable` creates a variable tensor with values [1, 2, 3]. Unlike constants, variables can be modified using assign operations. They are commonly used to represent trainable parameters in machine learning models.

Matrix Addition, Multiplication, and Element-wise Operations in TensorFlow:
TensorFlow provides several functions and operators to perform matrix operations efficiently. Here's a brief overview:

1. Matrix Addition:
   - TensorFlow provides the `tf.add` function or the `+` operator for element-wise addition of tensors of the same shape.

2. Matrix Multiplication:
   - TensorFlow provides the `tf.matmul` function or the `@` operator for matrix multiplication.
   - For element-wise multiplication, you can use the `tf.multiply` function or the `*` operator.

3. Element-wise Operations:
   - TensorFlow provides various element-wise operations such as `tf.add`, `tf.subtract`, `tf.multiply`, `tf.divide`, and more.
   - These operations perform element-wise operations on tensors of the same shape.

Example of Matrix Multiplication and Element-wise Addition:
```python
import tensorflow as tf

# Define two tensors
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = tf.matmul(tensor1, tensor2)
print("Matrix Multiplication:")
print(matrix_product)

# Element-wise addition
elementwise_sum = tf.add(tensor1, tensor2)
print("\nElement-wise Addition:")
print

In [6]:
!pip install tensorflow

#Q:2
import tensorflow as tf

# Create a normal matrix A with dimensions 2x2
matrix_A = tf.random.normal(shape=(2, 2))
print("Matrix A:")
print(matrix_A)

# Create a Gaussian matrix B with dimensions 2x2
matrix_B = tf.random.truncated_normal(shape=(2, 2))
print("\nMatrix B:")
print(matrix_B)

# Create a matrix C with dimensions 2x2, drawn from normal distribution
mean = 2.0
stddev = 0.1
matrix_C = tf.random.normal(shape=(2, 2), mean=mean, stddev=stddev)
print("\nMatrix C:")
print(matrix_C)

# Perform matrix addition between matrix A and matrix B
matrix_D = tf.add(matrix_A, matrix_B)
print("\nMatrix D (A + B):")
print(matrix_D)

# Perform matrix multiplication between matrix C and matrix D
matrix_E = tf.matmul(matrix_C, matrix_D)
print("\nMatrix E (C * D):")
print(matrix_E)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 2.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 64.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 77.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 64.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 24.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 47.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 57.0 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 66.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━

2023-06-27 19:33:46.059041: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-27 19:33:46.134621: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-27 19:33:46.135777: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-27 19:33:47.281991: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


Matrix A:
tf.Tensor(
[[ 0.06079669  1.4565115 ]
 [-2.1583061   0.3097592 ]], shape=(2, 2), dtype=float32)

Matrix B:
tf.Tensor(
[[ 0.31562516  0.27185962]
 [-1.7925876  -0.3786411 ]], shape=(2, 2), dtype=float32)

Matrix C:
tf.Tensor(
[[2.101784  2.017697 ]
 [2.1123517 1.9287479]], shape=(2, 2), dtype=float32)

Matrix D (A + B):
tf.Tensor(
[[ 0.37642184  1.7283711 ]
 [-3.9508939  -0.0688819 ]], shape=(2, 2), dtype=float32)

Matrix E (C * D):
tf.Tensor(
[[-7.1805496  3.49368  ]
 [-6.825143   3.5180717]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf

# Create a matrix F with dimensions 2x2, initialized with random values
matrix_F = tf.random.uniform(shape=(2, 2))
print("Matrix F:")
print(matrix_F)

# Calculate the transpose of matrix F and store the result in matrix G
matrix_G = tf.transpose(matrix_F)
print("\nMatrix G (Transpose of F):")
print(matrix_G)

# Calculate the element-wise exponential of matrix F and store the result in matrix H
matrix_H = tf.exp(matrix_F)
print("\nMatrix H (Exponential of F):")
print(matrix_H)

# Create a matrix I by concatenating matrix F and matrix G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("\nMatrix I (Horizontal Concatenation of F and G):")
print(matrix_I)

# Create a matrix J by concatenating matrix F and matrix H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("\nMatrix J (Vertical Concatenation of F and H):")
print(matrix_J)
